### ISSUE TITLE
What if not using createIndexeddatabase()

### ISSUE THREAD

**Issue by kezenwa** [tintin10q/simple-indexedDB#1]
I see for one to create a new database, they use createIndexeddatabase() BUT we equally know that indexedDB would create a new database if it fails to open() .
So now I ask, what's the advantage of using your method createIndexeddatabase() , instead of just relying on indexedDB to auto-create the dattabase it's self ?

Asking because I plan making the class somewhat simplier while integrating into a custom app and I am looking to reduce redundancy

**Comment by tintin10q** [comment]
Let me know if I misunderstooth. But the 
main use of the `createIndexeddatabase` function is to create object stores for you. So this example creates a garden database and also the animals,  plants, trees and flowers object stores inside of the garden database.

```js
await createIndexeddatabase("garden", {
    animals: {keyPath: "id", autoIncrement: false},
    plants: {keyPath: "id", autoIncrement: true},
    trees: {autoIncrement: true},
    flowers: {}, // default = {keyPath: null, autoIncrement: false}
})
```

I think this is useful because then you can rely on these object stores being there afterwards and you don't think about the case that these object stores do not exist.

So the use of this function comes more from the object stores it creates then the database I think.

**Comment by tintin10q** [comment]
If you do not have any further questions I will close this issue in a week or so
